
#With default value every difficulty perk maxes out at difficulty 250
[general]
	#Mobs to include for the new light spawning rules.
	#Only prevention is possible. Meaning you cant allow mobs to spawn at higher light levels
	"Light list" = []
	#Should punish time skipping with e.g. bed, commands? If false, difficulty will increase by 0.1 regardless of skipped time.
	"Punish Time Skip" = true
	#Disable/Enable friendly fire for owned pets.
	FriendlyFire = false
	#Blacklist for pet you should't be able to give armor to. Pets from mods, which have custom armor should be included here.
	"Pet Blacklist" = []
	#Turn the light list whitelist to blacklist
	"Light list blacklist" = false
	#Treat pet blacklist as whitelist
	"Pet Whitelist" = false
	#Light level >= x will prevent mob spawning for defined mobs.
	#Range: 0 ~ 16
	Light = 7
	#Disable/Enables the whole difficulty scaling of this mod. Requires a mc restart
	"Enable difficulty scaling" = true
	#Handles increase in difficulty regarding current difficulty.
	#Format is <minimum current difficulty>-<increase every 2400 ticks>
	#Example ["0-0.01","10-0.1","30-0"]
	#So the difficulty increases by 0.01 every 2400 ticks (->0.1 per mc day) till it reaches a difficulty of 10.
	#Then it increases by 1 per mc day till it reaches 30 and then stops.
	"Difficulty Increase" = ["0-0.1"]
	#Time in ticks for which the difficulty shouldnt increase at the beginning. One full minecraft day is 24000 ticks
	"Difficulty Delay" = 0
	#Wether difficulty should only increase with at least one online players or not
	"Ignore Players" = false
	#Increase difficulty with time
	#Here untill its back as a gamerule
	"Difficulty toggle" = true

#Black/Whitelist for various stuff
[list]
	#By default the mod only modifies EntityMobs. Add other entities here if you want to apply modifications to them. Usage:
	#<entity registry name> followed by any of:
	#[ALL,ATTRIBUTES,ARMOR,HELDITEMS,BLOCKBREAK,USEITEM,LADDER,STEAL,SWIMMRIDE,TARGETVILLAGER,REVERSE].
	#Leave empty to apply them all and REVERSE to reverse all flags. Some flags do nothing for certain mobs!
	#example: minecraft:sheep|REVERSE|ATTRIBUTES will add sheep to attributes modification (since default is a blacklist)
	#or minecraft:sheep|ATTRIBUTES will add sheep to everything except attributes
	"More Entities" = ["exoticbirds:lyrebird", "exoticbirds:owl", "aquaculture:minnow", "exoticbirds:heron", "aquaculture:tambaqui", "mowziesmobs:lantern", "exoticbirds:woodpecker", "aquaculture:pink_salmon", "aquaculture:atlantic_herring", "minecraft:hoglin", "aquaculture:catfish", "minecraft:trader_llama", "mowziesmobs:barakoa_sunblocker_player", "twilightforest:wraith", "upgrade_aquatic:goose", "upgrade_aquatic:thrasher", "exoticbirds:kingfisher", "goblintraders:goblin_trader", "minecraft:horse", "dungeonsmod:pice", "aquaculture:brown_shrooma", "cavesandcliffs:axolotl", "upgrade_aquatic:glow_squid", "exoticbirds:peafowl", "minecraft:polar_bear", "exoticbirds:cockatoo", "upgrade_aquatic:nautilus", "aquaculture:muskellunge", "mowziesmobs:grottol", "twilightforest:bunny", "aquaculture:bayad", "aquaculture:brown_trout", "minecraft:llama", "minecraft:pig", "twilightforest:raven", "aquaculture:bluegill", "minecraft:turtle", "aquaculture:red_shrooma", "minecraft:sheep", "aquaculture:atlantic_halibut", "minecraft:ender_dragon", "twilightforest:winter_wolf", "exoticbirds:cassowary", "mowziesmobs:baby_foliaath", "dungeonsmod:sun", "minecraft:dolphin", "upgrade_aquatic:immortal_jellyfish", "minecraft:cod", "aquaculture:gar", "exoticbirds:gull", "aquaculture:red_grouper", "minecraft:donkey", "twilightforest:loyal_zombie", "upgrade_aquatic:box_jellyfish", "minecraft:squid", "exoticbirds:bluejay", "minecraft:skeleton_horse", "twilightforest:tiny_bird", "minecraft:cow", "mowziesmobs:barakoaya", "exoticbirds:booby", "aquaculture:rainbow_trout", "minecraft:bee", "mowziesmobs:barakoa_sunblocker", "aquaculture:perch", "upgrade_aquatic:ululu", "goblintraders:vein_goblin_trader", "exoticbirds:penguin", "minecraft:salmon", "upgrade_aquatic:lionfish", "mowziesmobs:barakoan_barakoana", "mowziesmobs:naga", "exoticbirds:pigeon", "twilightforest:quest_ram", "aquaculture:jellyfish", "minecraft:snow_golem", "minecraft:mooshroom", "mutantbeasts:mutant_snow_golem", "twilightforest:hydra", "exoticbirds:roadrunner", "minecraft:villager", "mowziesmobs:foliaath", "aquaculture:tuna", "mowziesmobs:frostmaw", "twilightforest:wild_boar", "mowziesmobs:ferrous_wroughtnaut", "exoticbirds:magpie", "minecraft:rabbit", "artifacts:mimic", "stalwart_dungeons:nether_keeper", "exoticbirds:kiwi", "dungeonsmod:crow", "aquaculture:piranha", "upgrade_aquatic:great_thrasher", "aquaculture:box_turtle", "exoticbirds:ostrich", "aquaculture:blackfish", "aquaculture:arapaima", "minecraft:strider", "minecraft:parrot", "cavesandcliffs:glow_squid", "exoticbirds:flamingo", "exoticbirds:crane", "exoticbirds:toucan", "mowziesmobs:barako", "twilightforest:bighorn_sheep", "twilightforest:mist_wolf", "minecraft:bat", "minecraft:wandering_trader", "upgrade_aquatic:perch", "aquaculture:carp", "aquaculture:pacific_halibut", "exoticbirds:robin", "exoticbirds:budgerigar", "minecraft:iron_golem", "twilightforest:hostile_wolf", "cavesandcliffs:goat", "aquaculture:pollock", "twilightforest:deer", "exoticbirds:pelican", "mutantbeasts:spider_pig", "mowziesmobs:barakoan_player", "dungeonsmod:extrapart", "aquaculture:arrau_turtle", "aquaculture:boulti", "exoticbirds:hummingbird", "aquaculture:capitaine", "exoticbirds:gouldianfinch", "upgrade_aquatic:cassiopea_jellyfish", "stacked_dimensions_warden:great_sculker", "upgrade_aquatic:flare", "twilightforest:squirrel", "minecraft:mule", "minecraft:zombie_horse", "exoticbirds:macaw", "aquaculture:atlantic_cod", "mutantbeasts:creeper_minion", "aquaculture:synodontis", "exoticbirds:kookaburra", "twilightforest:knight_phantom", "minecraft:cat", "minecraft:pufferfish", "aquaculture:starshell_turtle", "exoticbirds:swan", "minecraft:fox", "aquaculture:smallmouth_bass", "minecraft:tropical_fish", "exoticbirds:cardinal", "minecraft:ocelot", "twilightforest:penguin", "exoticbirds:duck", "minecraft:chicken", "minecraft:wolf", "mowziesmobs:barakoana", "minecraft:panda", "dungeonsmod:piranha", "upgrade_aquatic:pike"]
	#Treat LADDER flags as whitelist
	"Ladder Whitelist" = false
	#Treat USEITEM flags as whitelist
	"Item Use Whitelist" = false
	#Put the above flags here to completly disable them.
	"Flag Blacklist" = []
	#Treat ATTRIBUTES flags as whitelist
	"Attribute Whitelist" = false
	#Treat BLOCKBREAK flags as whitelist
	"Breaker Whitelist" = false
	#Treat HELDITEMS flags as whitelist
	"Held Equip Whitelist" = false
	#Treat STEAL flags as whitelist
	"Steal Whitelist" = false
	#Treat SWIMMRIDE flags as whitelist
	"Boat Whitelist" = false
	#Treat ARMOR flags as whitelist
	"Armor Equip Whitelist" = false
	#Treat TARGETVILLAGER flags as whitelist
	"Villager Whitelist" = false

#Debugging
[debug]
	#Enable showing of entity paths
	"Path Debugging" = false

#Settings for mod integration
[integration]
	#Should the scaling health mods difficulty system be used instead of this ones. (Requires scaling health mod)
	"Use Scaling Health Mod" = true
	#Should mobs be able to use techguns weapons. (Requires techguns mod)
	"Use Techguns Mod" = true
	#Should the coroutils repair block be used. (Requires coroutils mod)
	"Use CoroUtils Mod" = true
	#Should mobs be able to use weapons from the reforged mod. (Requires reforged mod)
	"Use Reforged Mod" = true

#Settings regarding custom ai for mobs
[ai]
	#Items which will be given to mobs who can break blocks. Empty list = no items. Syntax: id;weight
	"Breaking items" = ["minecraft:diamond_pickaxe;1"]
	#Should mobs be able to break tile entities? Evaluated before the break list
	"Break Tiles" = true
	#Chance for a mob to be able to break blocks
	#Range: 0.0 ~ 1.0
	"Breaker Chance" = 0.3
	#List for of pairs containing which mobs auto target others. Syntax is [mob id]-[mob id] where second value is the target.
	# e.g. minecraft:zombie-minecraft:skeleton makes all zombies target skeletons
	"Auto Target List" = []
	#Difficulty at which mobs are able to steal items
	"Difficulty Steal AI" = 0.0
	#Use the block breaking sound instead of a knocking sound
	Sound = false
	#Initial cooldown for block breaking mobs
	"Breaker Initial Cooldown" = 120
	#Treat Block Whitelist as Blocklist
	"Block as Blacklist" = false
	#Chance for a mob to be able to steal items
	#Range: 0.0 ~ 1.0
	"Stealer Chance" = 0.3
	#Chance for neutral mobs to be aggressive
	#Range: 0.0 ~ 1.0
	"Neutral Aggressive Chance" = 0.2
	#Difficulty at which mobs are able to break blocks
	"Difficulty Break AI" = 0.0
	#Whitelist for blocks, which can be actively broken. Usage: <registry name;classname;tag> put "!" infront to exclude blocks
	#If you includery common blocks (like grass blocks) the pathfinding will be a bit strange
	"Block Whitelist" = ["forge:glass", "forge:glass_panes", "minecraft:fence_gates", "forge:fence_gates", "minecraft:wooden_doors"]
	#Delay for the coroutil repair block. Coroutil integration needs to be enabled
	"Repair Ticks" = 500
	#Cooldown for breaking blocks
	"Breaker Cooldown" = 20

#Configs regarding mobs spawning with equipment
[equipment]
	#Base chance for each armor pieces to get enchanted
	#Range: 0.0 ~ 1.0
	"Enchanting Chance" = 0.2
	#Specify min and max enchanting levels according to difficulty. difficulty-minLevel-maxLevel
	"Enchanting Calc" = ["0-5-10", "25-5-15", "50-10-17", "100-15-25", "200-20-30", "250-30-35"]
	#Adds additional x*difficulty% to base enchanting chance
	"Enchanting Addition" = 0.2
	#Base chance that a mob can have one piece of armor
	#Range: 0.0 ~ 1.0
	"Equipment Chance" = 0.1
	#Chance for mobs to have a weapon
	#Range: 0.0 ~ 1.0
	"Weapon Chance" = 0.05
	#Should mobs drop the armor equipped through this mod? (Other methods e.g. through vanilla is not included)
	"Should drop equipment" = false
	#Adds additional x*difficulty% to base item chance
	"Item Chance add" = 0.2
	#Base chance for each additional armor pieces
	#Range: 0.0 ~ 1.0
	"Additional Equipment Chance" = 0.3
	#Blacklist for items mobs should never be able to use.
	#Use as in using the item similar to players (e.g. shooting bows)
	"Item Use Blacklist" = ["bigbrain:buckler"]
	#Chance for mobs to have an item in offhand
	#Range: 0.0 ~ 1.0
	"Item Equip Chance" = 0.05
	#Blacklist for mods. Add modid to prevent items from that mod being equipped. (For individual items use the equipment.json)
	"Item Blacklist" = []
	#Turn the use blacklist into a whitelist
	"Item Use Whitelist" = false
	#Adds additional x*difficulty% to base equip chance
	"Equipment Addition" = 0.3
	#Adds additional x*difficulty% to base weapon chance
	"Weapon Chance Add" = 0.3
	#Use blacklist as whitelist
	"Item Whitelist" = false
	#Blacklist for specific mobs and items they shouldnt use (e.g. skeletons already use bows)
	#<entity registry name-item>
	#For different items but same entity use multiple lines
	#Some special names are BOW, TRIDEN, CROSSBOW refering to every bow/trident/crossbow item (So you dont need to type e.g. every bow item)
	"Entity Item Use Blacklist" = ["minecraft:drowned;TRIDENT", "minecraft:illusioner;BOW", "minecraft:piglin;CROSSBOW", "minecraft:pillager;CROSSBOW", "minecraft:skeleton;BOW", "minecraft:snow_golem;minecraft:snowball", "minecraft:stray;BOW", "minecraft:wither_skeleton;BOW"]

#Settings for attribute modifiers
[attributes]
	#Maximum increase in magic resistance. Magic reduction is percentage
	#Range: 0.0 ~ 1.0
	"Max Magic Resistance" = 0.4
	#Maximum increase in knockback
	"Max Knockback" = 0.5
	#Magic resistance will be increased by difficulty*0.0016*x. Set to 0 to disable
	"Magic Resistance Increase" = 1.0
	#Speed will be increased by difficulty*0.0008*x. Set to 0 to disable
	"Speed Increase" = 1.0
	#Damage will be multiplied by difficulty*0.008*x. Set to 0 to disable
	"Damage Increase Multiplier" = 1.0
	#Projectile damage will be multiplied by maximum of this
	"Max Projectile Damage" = 2.0
	#Round health to the nearest x. Set to 0 to disable
	"Round HP" = 0.5
	#Projectile Damage will be multiplied by 1+difficulty*0.008*x. Set to 0 to disable
	"Projectile Damage Increase" = 1.0
	#Health will be multiplied by difficulty*0.016*x. Set to 0 to disable
	"Health Increase Multiplier" = 1.0
	#Damage will be multiplied by at maximum this. Set to 0 means no limit
	"Max Damage Increase" = 3.0
	#Health will be multiplied by at maximum this. Set to 0 means no limit
	"Max Health Increase" = 5.0
	#Knockback will be increased by difficulty*0.002*x. Set to 0 to disable
	"Knockback Increase" = 1.0
	#Maximum increase in speed
	#Range: 0.0 ~ 1.0
	"Max Speed" = 0.1

