
[general]
	#Try to spawn a random monster and wake the player when sleeping in a dark area.
	"Bad Dreams" = true
	#Allow configuration for every option that could normally prevent the player from sleeping.
	"Sleeping Checks" = true
	#A bunch of options that may happen when the player wakes up from sleeping in a bed.
	"Wake Up Actions" = true

[bad_dreams]
	#Chance to spawn a monster. Higher values make it more likely to happen.
	#Range: 0 ~ 128
	"Spawn Monster Chance" = 12
	#Range to spawn a monster in from the bed. Increasing the range makes it a lot less likely for a monster to spawn.
	#Range: 0 ~ 16
	"Spawn Monster Range" = 2
	#Possible monsters to spawn. One entry is chosen at random.
	#Format for every entry is "<namespace>:<path>,<weight>". Path may use asterisk as wildcard parameter.
	"Spawnable Monsters" = ["minecraft:zombie,2", "minecraft:skeleton,1", "minecraft:spider,1"]

[wake_up_actions]
	#Should the player be healed when waking up.
	"Heal Player" = true
	#Amount of health the player should regain. Set to 0 to fully heal.
	#Range: > 0
	"Heal Amount" = 0
	#Should the player loose some food after waking up.
	"Loose Food" = true
	#Amount of food to loose when waking up. Set to 0 to completely starve the player.
	#Range: > 0
	"Food Amount" = 3
	#Clear potion effects after the player wakes up.
	#Allowed Values: NONE, POSITIVE, NEGATIVE, ALL
	"Clear Effects" = "ALL"
	#Blacklist to prevent potion effects from being removed after waking up.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter.
	"Effects Not To Clear" = ["minecraft:bad_omen", "minecraft:conduit_power"]
	#Should custom potion effects be applied to the player after waking up.
	"Apply Effects" = true
	#Potion effects to be given to the player after waking up. Values are based on the "/effect" command.
	#Format for every entry is "<namespace>:<path>,[<seconds>],[<amplifier>],[<hideParticles>]". Path may use asterisk as wildcard parameter.
	"Effects To Apply" = ["minecraft:speed"]

[sleeping_checks]
	#Check if the player is close enough to the bed.
	"Perform Range Check" = false
	#Check if the bed has enough open space above it.
	"Perform Obstruction Check" = true
	#Check if monsters are nearby.
	"Perform Monster Check" = true
	#Should monsters preventing the player from sleeping glow.
	"Make Monsters Glow" = true
	#Duration in seconds for which the monsters nearby will glow.
	#Range: > 0
	"Monster Glowing Duration" = 3
	#Should sleeping be allowed when named monsters are nearby.
	"Allow Named Monsters" = true
	#Should sleeping be possible when persistent monsters (unable to despawn) are nearby.
	"Allow Persistent Monsters" = true

